site_name: Mukh Documentation
site_description: A Python library for face analysis, detection, reenactment, and deepfake detection
site_author: Ishan Dutta
site_url: https://ishandutta0098.github.io/mukh/
repo_url: https://github.com/ishandutta0098/mukh
repo_name: ishandutta0098/mukh

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
  - Examples:
    - Face Detection: examples/face-detection.md
    - Face Reenactment: examples/face-reenactment.md
    - Deepfake Detection: examples/deepfake-detection.md
    - Pipelines: examples/pipelines.md
  - API Reference:
    - Core: api/core.md
    - Face Detection: api/face-detection.md
    - Face Reenactment: api/face-reenactment.md
    - Deepfake Detection: api/deepfake-detection.md
  - Contributing: contributing.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ishandutta0098/mukh
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/mukh/

# GitHub Pages deployment
site_dir: site 